Update .chezmoitemplates/file_location Update .chezmoitemplates/file_title Update .shell/actions/fastfetch.sh Update .shell/actions/fzf.sh Update .shell/actions/oh-my-posh.sh Update .shell/actions/zoxide.sh Remove .shell/aliases/bat Add .shell/aliases/bat Remove .shell/aliases/cheatsheet Add .shell/aliases/cheatsheet Remove .shell/aliases/fd Add .shell/aliases/fd Remove .shell/aliases/gpg Add .shell/aliases/gpg Remove .shell/aliases/man Add .shell/aliases/man Remove .shell/aliases/tokei Add .shell/aliases/tokei Remove .shell/aliases/vim Add .shell/aliases/vim Remove .shell/aliases/zoxide Add .shell/aliases/zoxide Remove .shell/footers/99-fastfetch.sh Add .shell/footers/99-fastfetch.sh Update .shell/functionsrc Remove .shell/headers/01-cargo.sh Add .shell/headers/01-cargo.sh Remove .shell/headers/01-fzf.sh Add .shell/headers/01-fzf.sh Remove .shell/headers/01-zoxide.sh Add .shell/headers/01-zoxide.sh Remove .shell/headers/10-oh-my-posh.sh Add .shell/headers/10-oh-my-posh.sh Change attributes of .shell/actions/cargo.sh Change attributes of .shell/aliases/eza Change attributes of .shell/aliases/fzf Change attributes of .shell/aliases/hardcode-tray Change attributes of .shell/aliases/pacman Change attributes of .shell/aliases/proto Change attributes of .shell/aliases/reflector Change attributes of .shell/aliases/ripgrep Change attributes of .shell/aliases/yay Change attributes of .shell/envs/cargo Change attributes of .shell/envs/dotnet Change attributes of .shell/envs/editor Change attributes of .shell/envs/fzf Change attributes of .shell/envs/oh-my-posh Change attributes of .shell/envs/pnpm Change attributes of .shell/envs/proto Change attributes of .shell/shells/bash

diff --git a/dot_shell/functionsrc.tmpl b/dot_shell/functionsrc.tmpl
--- a/dot_shell/functionsrc.tmpl
+++ b/dot_shell/functionsrc.tmpl
@@ -9,9 +9,9 @@ is_not_equal_string() { [[ "${1}" != "${2}" ]] }
 is_equal() { [[ ${1} -eq ${2} ]] }
 is_not_equal() { [[ ${1} -ne ${2} ]] }
 is_lower_than() { [[ ${1} -lt ${2} ]] }
-is_equal_or_lower_than() { [[ ${1} -le ${2} ]] }
+is_lower_than_equal() { [[ ${1} -le ${2} ]] }
 is_greater_than() { [[ ${1} -gt ${2} ]] }
-is_equal_or_greater_than() { [[ ${1} -ge ${2} ]] }
+is_greater_than_equal() { [[ ${1} -ge ${2} ]] }
 
 is_file() { is_not_empty_string "${1}" && [[ -f "${1}" ]] }
 is_executable() { is_not_empty_string "${1}" && [[ -x "${1}" ]] }
@@ -27,11 +27,17 @@ contains_string() {
   [[ "${1}" =~ "${2}" ]]
 }
 #---------- File ----------------------------------------------------#
-try_load_file() { is_file "${1}" && source "${1}"; }
+try_load_file() {
+  if is_file "${1}"; then
+    source "${1}" || warn "Couldn't load file: '$(orange "${1}")'"
+  else
+    debug "Skip: '$(orange "${1}")' is not file"
+  fi
+}
 #---------- Directory -----------------------------------------------#
 ensure_dir_exists() { is_not_empty_string "${1}" && mkdir -pv "${1}"; }
 #---------- Terminal ------------------------------------------------#
-command_exists() { type "${1}" &>/dev/null; }
+command_exists() { type "${1}" &>/dev/null; is_equal "${?}" "0"; }
 
 is_shell() { contains_string "$(ps -p $$ -ocmd=)" "${1}"; }
 is_bash() { is_shell "bash"; }
@@ -59,5 +65,54 @@ to_completions() {
   ensure_dir_exists "${SHELL_DIR_COMPLETION}"
   cat > "${SHELL_DIR_COMPLETION}/${1}"
   is_non_zero_size "${SHELL_DIR_COMPLETION}/${1}" && echo "Created '${1}' in '${SHELL_DIR_COMPLETION}'"
+}
+#---------- Log -----------------------------------------------------#
+# ${1} - Verbosity level
+# ${2} - Message
+# ${3} - Log type (optional)
+# ${4} - Log type color (optional)
+log_shell() {
+  # Verbosity/Message empty; return error
+  if is_empty_string "${1}" || is_empty_string "${2}"; then
+    return 1
+  fi
+
+  # Verbosity not compatible; return other
+  if is_greater_than "${1}" "${SHELL_VERBOSITY:-2}"; then
+    return 126
+  fi
+
+  local color=${4:-"$(tput setab 232;tput setaf 255;tput bold)"}
+  local reset="$(tput sgr0)"
+  local msg="${3:-"[MESSAGE]"}"
+  echo -e "$(colorize "${color}" "${msg}" "${reset}") --- ${2}"
+  return 0
+}
+
+debug() { log_shell "3" "${@}" "[VERBOSE]" "$(tput setab 55;tput bold)"; }
+
+info() { log_shell "2" "${@}" "[INFO]" "$(tput setab 32;tput bold)"; }
+
+warn() { log_shell "2" "${@}" "[WARN]" "$(tput setab 178;tput setaf 9;tput bold)"; }
+
+error() { log_shell "1" "${@}" "[ERROR]" "$(tput setab 88;tput bold)"; }
+
+critical() { log_shell "0" "${@}" "[CRITICAL]" "$(tput setab 160;tput bold)"; }
+#---------- Color ---------------------------------------------------#
+# https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit
+colorize() { printf "%s" "${@}"; }
+
+orange() {
+  local color="$(tput setaf 166)"
+  local reset="$(tput sgr0)"
+  echo -e "$(colorize "${color}" "${*}" "${reset}")";
+  return 0
+}
+
+purple() {
+  local color="$(tput setaf 128)"
+  local reset="$(tput sgr0)"
+  echo -e "$(colorize "${color}" "${*}" "${reset}")";
+  return ${shell_exit_codes[success]}
 }
 #--------------------------------------------------------------------#
